// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/v1/proto/sensor.service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TempRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TempRequest) Reset() {
	*x = TempRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_sensor_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TempRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempRequest) ProtoMessage() {}

func (x *TempRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_sensor_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempRequest.ProtoReflect.Descriptor instead.
func (*TempRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_sensor_service_proto_rawDescGZIP(), []int{0}
}

type TempResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TempResponse) Reset() {
	*x = TempResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_sensor_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TempResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempResponse) ProtoMessage() {}

func (x *TempResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_sensor_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempResponse.ProtoReflect.Descriptor instead.
func (*TempResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_sensor_service_proto_rawDescGZIP(), []int{1}
}

func (x *TempResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_api_v1_proto_sensor_service_proto protoreflect.FileDescriptor

var file_api_v1_proto_sensor_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x0d, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x42, 0x0a,
	0x0d, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31,
	0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x10, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_v1_proto_sensor_service_proto_rawDescOnce sync.Once
	file_api_v1_proto_sensor_service_proto_rawDescData = file_api_v1_proto_sensor_service_proto_rawDesc
)

func file_api_v1_proto_sensor_service_proto_rawDescGZIP() []byte {
	file_api_v1_proto_sensor_service_proto_rawDescOnce.Do(func() {
		file_api_v1_proto_sensor_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_proto_sensor_service_proto_rawDescData)
	})
	return file_api_v1_proto_sensor_service_proto_rawDescData
}

var file_api_v1_proto_sensor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_proto_sensor_service_proto_goTypes = []interface{}{
	(*TempRequest)(nil),  // 0: api.TempRequest
	(*TempResponse)(nil), // 1: api.TempResponse
}
var file_api_v1_proto_sensor_service_proto_depIdxs = []int32{
	0, // 0: api.SensorService.TempSensor:input_type -> api.TempRequest
	1, // 1: api.SensorService.TempSensor:output_type -> api.TempResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_proto_sensor_service_proto_init() }
func file_api_v1_proto_sensor_service_proto_init() {
	if File_api_v1_proto_sensor_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_proto_sensor_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TempRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_sensor_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TempResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_proto_sensor_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_proto_sensor_service_proto_goTypes,
		DependencyIndexes: file_api_v1_proto_sensor_service_proto_depIdxs,
		MessageInfos:      file_api_v1_proto_sensor_service_proto_msgTypes,
	}.Build()
	File_api_v1_proto_sensor_service_proto = out.File
	file_api_v1_proto_sensor_service_proto_rawDesc = nil
	file_api_v1_proto_sensor_service_proto_goTypes = nil
	file_api_v1_proto_sensor_service_proto_depIdxs = nil
}
